### ISSUE TITLE
deprecate formatAtsign() in AtUtils and move the functionality to fixAtSign()

### ISSUE THREAD

**Issue by srieteja** [atsign-foundation/at_tools#293]
### Is your feature request related to a problem? Please describe.

There are currently two methods:
- formatAtsign(): which prefixes an atsign with '@' when it's missing one
- fixAtsign(): which performs all other checks/fixes atsign to match a standard format

To end up with a correctly formatted atsign one needs to use the two of these methods and it can be confusing. 

### Describe the solution you'd like

Deprecate formatAtsign() and move it's functionality to fixAtsign(), which allows a simpler and a more cleaner mechanism to format atsign's

### Task checklist

- [x] deprecate formatAtsign()
- [x] move it's functionality to fixAtSign()
- [x] integration test with all other packages e.g. at_server, at_client, at_onboarding_cli, etc
- [x] publish at_utils with this change
